export const CARTS_FETCH_REQUEST = "CARTS_FETCH_REQUEST";
export const CARTS_FETCH_SUCCESS = "CARTS_FETCH_SUCCESS";
export const CARTS_FETCH_ERROR = "CARTS_FETCH_ERROR";

export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_ERROR = "CART_ADD_ERROR";

export const CART_DELETE_REQUEST = "CART_DELETE_REQUEST";
export const CART_DELETE_SUCCESS = "CART_DELETE_SUCCESS";
export const CART_DELETE_ERROR = "CART_DELETE_ERROR";

export const CART_UPDATE_REQUEST = "CART_UPDATE_REQUEST";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";
export const CART_UPDATE_ERROR = "CART_UPDATE_ERROR";

export const CART_CLEAR = "CART_CLEAR";
