export const FETCH_PRODUCTS_ASYNC = "FETCH_PRODUCTS_ASYNC";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const VIEW_PRODUCT = "VIEW_PRODUCT";

export const SEARCH_FILTER = "SEARCH_FILTER";
export const VOTE_FILTER = "VOTE_FILTER";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const STATUS_FILTER = "STATUS_FILTER";
