export const FETCH_PRODUCTS_ASYNC = "FETCH_PRODUCTS_ASYNC";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const SEARCH_FILTER = "SEARCH_FILTER";
export const VOTE_FILTER = "VOTE_FILTER";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const STATUS_FILTER = "STATUS_FILTER";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_ASYNC = "GET_PRODUCT_BY_ID_ASYNC";
