export const FETCH_PRODUCTS_ASYNC = "FETCH_PRODUCTS_ASYNC";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const SEARCH_FILTER = "SEARCH_FILTER";
export const VOTE_FILTER = "VOTE_FILTER";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const STATUS_FILTER = "STATUS_FILTER";
