export const VERIFY_CODE_REQUEST = "VERIFY_CODE_REQUEST";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_ERROR = "VERIFY_CODE_ERROR";
export const VERIFY_CODE_RESET = "VERIFY_CODE_RESET";
