export const FETCH_USERS_ASYNC = 'FETCH_USER_ASYNC';
export const FETCH_USERS_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const GET_USER_BY_ID_ASYNC = 'GET_USER_BY_ID_ASYNC';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';

export const SEARCH_FILTER = 'SEARCH_FILTER';
export const ROLE_FILTER = 'ROLE_FILTER';
export const STATUS_FILTER = 'STATUS_FILTER';