export const FETCH_USERS_ASYNC = 'FETCH_USER_ASYNC';
export const FETCH_USERS_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USER_ERROR';

export const SAVE_USER = 'SAVE_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';

export const SEARCH_FILTER = 'SEARCH_FILTER';
export const ROLE_FILTER = 'ROLE_FILTER';
export const STATUS_FILTER = 'STATUS_FILTER';